In [12]:
import pandas as pd

# read json of yelp_academic_dataset_business.json
df_business = pd.read_json('data/yelp_academic_dataset_business.json', lines=True)

In [13]:
'hmart' in df_business['name'].unique()

False

In [14]:
# store hmart business id
substrings = ['h-mart', 'hmart', 'h mart']
df_business[df_business['name'].str.lower().apply(lambda x: any(x.startswith(substr) for substr in substrings))]

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,is_open,attributes,categories,hours
43575,HIAJ2mnlm_pP38_8GbgQ5g,Hmart,1138 Bristol Oxford Valley Rd,Levittown,PA,19057,40.165707,-74.876063,4.0,80,1,"{'BusinessAcceptsCreditCards': 'True', 'Busine...","Restaurants, International Grocery, Korean, Se...","{'Monday': '9:0-20:0', 'Tuesday': '9:0-20:0', ..."
53706,1UKBAgYxI9Qax3AA4ULw_w,H Mart - Philadelphia,"6201 North Front St, Ste 124",Philadelphia,PA,19120,40.045022,-75.117504,4.5,33,1,"{'RestaurantsDelivery': 'True', 'Ambience': '{...","Korean, Food, Restaurants, Grocery, Specialty ...","{'Monday': '9:0-21:0', 'Tuesday': '9:0-21:0', ..."
102234,-wlmZ-b35UJ-GY-59NDxyw,H Mart - Elkins Park,7320 Old York Rd.,Elkins Park,PA,19027,40.063035,-75.136916,4.0,155,1,"{'BusinessParking': '{'garage': False, 'street...","Food, Pan Asian, Grocery, Korean, Seafood Mark...","{'Monday': '8:0-20:0', 'Tuesday': '8:0-20:0', ..."
111313,GNYNs8pu3J-GaSKLQueQSg,H Mart - Upper Darby,7050 Terminal Sq.,Upper Darby,PA,19082,39.961243,-75.262895,4.0,163,1,"{'Ambience': '{'romantic': False, 'intimate': ...","Ethnic Food, Korean, Food Court, Seafood Marke...","{'Monday': '8:30-20:0', 'Tuesday': '8:30-20:0'..."
112256,iXMuh6475dWdvHNIaFs3Xw,H-Mart,570 - 3803 Calgary Trail NW,Edmonton,AB,T6J 5M8,53.470876,-113.494718,3.0,16,1,"{'BusinessParking': '{'garage': False, 'street...","Bakeries, Restaurants, Grocery, Food Court, Fo...","{'Monday': '9:0-22:0', 'Tuesday': '9:0-22:0', ..."
133223,t7lXDRAytv_pq5FLWSxtaQ,H Mart - Cherry Hill,1720 Rt. 70 East.,Cherry Hill,NJ,08003,39.908325,-74.976585,4.0,94,1,"{'WheelchairAccessible': 'True', 'RestaurantsT...","Food, Food Court, Specialty Food, Restaurants,...","{'Monday': '8:30-20:0', 'Tuesday': '8:30-20:0'..."

In [16]:
hmart_ids = df_business[df_business['name'].str.lower().apply(lambda x: any(x.startswith(substr) for substr in substrings))]['business_id'].values
hmart_ids

array(['HIAJ2mnlm_pP38_8GbgQ5g', '1UKBAgYxI9Qax3AA4ULw_w',
       '-wlmZ-b35UJ-GY-59NDxyw', 'GNYNs8pu3J-GaSKLQueQSg',
       'iXMuh6475dWdvHNIaFs3Xw', 't7lXDRAytv_pq5FLWSxtaQ'], dtype=object)

In [10]:
# partially read json of yelp_academic_dataset_review.json

import json
from itertools import islice

filename = "data/yelp_academic_dataset_review.json"
with(open(filename)) as f:
    objects = (json.loads(line) for line in f)
    objects = islice(objects, 200)
    rows = list(objects)

# Convert to pandas DataFrame
df_review = pd.DataFrame(rows)

df_review

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,KU_O5udG6zpxOg-VcAEodg,mh_-eMZ6K5RLWhZyISBhwA,XQfwVwDr-v0ZS3_CbbE5Xw,3.0,0,0,0,"If you decide to eat here, just be aware it is...",2018-07-07 22:09:11
1,BiTunyQ73aT9WBnpR9DZGw,OyoGAe7OKpv6SyGZT5g77Q,7ATYjTIgM3jUlt4UM3IypQ,5.0,1,0,1,I've taken a lot of spin classes over the year...,2012-01-03 15:28:18
2,saUsX_uimxRlCVr67Z4Jig,8g_iMtfSiwikVnbP2etR0A,YjUWPpI6HXG530lwP-fb2A,3.0,0,0,0,Family diner. Had the buffet. Eclectic assortm...,2014-02-05 20:30:30
3,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5.0,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
4,Sx8TMOWLNuJBWer-0pcmoA,bcjbaE6dDog4jkNY91ncLQ,e4Vwtrqf-wpJfwesgvdgxQ,4.0,1,0,1,Cute interior and owner (?) gave us tour of up...,2017-01-14 20:54:15
...,...,...,...,...,...,...,...,...,...
195,c9uUji8cUjVqkMisIfHjyg,zMeM0HTnNfjBffhgm-3EBA,dBCNUSbz5-8nQNrxWo5deg,4.0,0,0,0,I love this place. The food is great and the ...,2011-05-27 17:36:12
196,ZNZMWPfPdbbM7dhZlIpoFA,zq2nd0H1dVzi3bta4Zepuw,JvawJ9bSr22xn4R9oLvl_w,4.0,0,0,0,Took a while to get actual service but once we...,2015-05-26 06:01:17
197,IJCYT9dRjuBvY-BJufFnNg,hWDybu_KvYLSdEFzGrniTw,roc-xyyzN5b_nImb0NdRLQ,4.0,6,5,5,"As airport grab-and-go restaurants are, Earl d...",2015-01-03 23:16:09
198,clKHv1f5cIsaJVJPdKKHZg,f0fqCwb_QAJUPm-K95Mk2g,NdqATFd0JsFzEOD8Z8pa5w,5.0,2,0,1,"WOW! What a fantastic place! Food A+, Servic...",2014-08-25 00:52:32
199,cOcKS8BQ7yjOJPatqK2OOQ,Lc5U0qetusunJZ0NgNO_Iw,Y2rYM2crYfTC25y6iquPgw,5.0,0,0,0,I stopped in for dinner and a drink & was thor...,2015-08-30 16:34:23